---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: kube-system
spec:
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads (excluding daemons)
  ttlSecondsUntilExpired: 604800 # expire nodes after 7 days (in seconds) = 7 * 60 * 60 * 24
  limits:
    resources:
      cpu: 200 # limit to 100 CPU cores the maximum cluster usage
  requirements:
    # Include general purpose instance families
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: ["t3","c5a"]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values:
        - large
        - xlarge
        - 2xlarge
    - key: kubernetes.io/arch 
      operator: In 
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
  namespace: karpenter
spec:
  subnetSelector:
    karpenter.sh/discovery: "true"
  securityGroupSelector:
    aws:eks:cluster-name: "devops-labs" #CHANGE THIS VALUE TO CLUSTER NAME
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        iops: 3000
        deleteOnTermination: true
        throughput: 125
